"use client";

import React, { useState } from "react";
import { Sparkles, CheckCircle, AlertTriangle, ArrowRight, Loader2, Plus } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/toast";
import { analyzeInteractionAction } from "@/app/actions/ai";
import { createTaskAction } from "@/app/actions/tasks";
import { AiAnalysisOutput } from "@/lib/validations";

interface AiCopilotWidgetProps {
  contactId: string;
}

export function AiCopilotWidget({ contactId }: AiCopilotWidgetProps) {
  const { toast } = useToast();
  const [notes, setNotes] = useState("");
  const [analyzing, setAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<AiAnalysisOutput | null>(null);
  const [convertingIndex, setConvertingIndex] = useState<number | null>(null);
  const [addedTasks, setAddedTasks] = useState<Set<number>>(new Set());

  const handleAnalyze = async () => {
    if (!notes.trim() || notes.trim().length < 5) {
      toast({
        title: "Input Required",
        description: "Please enter call or meeting notes to analyze.",
        type: "warning",
      });
      return;
    }

    setAnalyzing(true);
    setAnalysis(null);
    setAddedTasks(new Set());

    const result = await analyzeInteractionAction(contactId, notes.trim());
    setAnalyzing(false);

    if (result.success && result.analysis) {
      setAnalysis(result.analysis);
      toast({
        title: "Analysis Complete",
        description: "Structured insights and action items generated.",
        type: "success",
      });
    } else {
      toast({
        title: "Analysis Failed",
        description: result.error || "Could not analyze notes.",
        type: "error",
      });
    }
  };

  const handleCreateTask = async (
    item: AiAnalysisOutput["actionItems"][0],
    index: number
  ) => {
    setConvertingIndex(index);
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + item.dueInDays);

    const result = await createTaskAction({
      title: item.task,
      priority: item.priority,
      contact_id: contactId,
      due_date: dueDate.toISOString(),
      description: "Generated by AI Sales Copilot based on interaction notes.",
    });

    setConvertingIndex(null);

    if (result.success) {
      setAddedTasks((prev) => new Set(prev).add(index));
      toast({
        title: "Task Created",
        description: `Added "${item.task}" to workspace tasks.`,
        type: "success",
      });
    } else {
      toast({
        title: "Task Creation Failed",
        description: result.error,
        type: "error",
      });
    }
  };

  const sentimentColor = (s: string) => {
    switch (s) {
      case "positive":
        return "success";
      case "hesitant":
        return "warning";
      case "negative":
        return "destructive";
      default:
        return "secondary";
    }
  };

  const urgencyColor = (u: string) => {
    switch (u) {
      case "high":
        return "destructive";
      case "medium":
        return "warning";
      default:
        return "secondary";
    }
  };

  return (
    <Card className="border-primary/20 bg-primary/5">
      <CardHeader className="p-4 pb-2">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <CardTitle className="text-xs font-semibold uppercase tracking-wider text-primary">
            AI Sales Copilot
          </CardTitle>
        </div>
        <p className="text-[11px] text-muted-foreground">
          Analyze sales meetings or call transcripts to extract structured sentiment, urgency, and actionable next steps.
        </p>
      </CardHeader>

      <CardContent className="p-4 pt-2 space-y-3">
        <div>
          <textarea
            placeholder="Paste discussion notes, call summary, or customer email here (e.g. 'Customer is interested in 3 excavators but concerned about delivery timeline and standard 30-day payment terms...')"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            rows={3}
            className="w-full rounded-md border border-input bg-background p-2.5 text-xs placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          />
        </div>

        <div className="flex items-center justify-between">
          <span className="text-[10px] text-muted-foreground">
            Isolated tenant context • Schema validated output
          </span>
          <Button
            size="sm"
            onClick={handleAnalyze}
            disabled={analyzing}
            className="text-xs h-7 gap-1.5"
          >
            {analyzing ? (
              <>
                <Loader2 className="h-3 w-3 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <Sparkles className="h-3.5 w-3.5" />
                Analyze Interaction
              </>
            )}
          </Button>
        </div>

        {/* Structured Results Display */}
        {analysis && (
          <div className="mt-3 pt-3 border-t border-primary/10 space-y-3 bg-card p-3 rounded-lg border shadow-xs animate-in fade-in-50">
            {/* Sentiment & Urgency Badges */}
            <div className="flex items-center gap-2">
              <span className="text-xs font-medium text-muted-foreground">Sentiment:</span>
              <Badge variant={sentimentColor(analysis.sentiment)} className="text-[10px] capitalize">
                {analysis.sentiment}
              </Badge>

              <span className="text-xs font-medium text-muted-foreground ml-2">Urgency:</span>
              <Badge variant={urgencyColor(analysis.urgencyLevel)} className="text-[10px] capitalize">
                {analysis.urgencyLevel}
              </Badge>
            </div>

            {/* Executive Summary */}
            <div>
              <span className="text-[10px] font-semibold uppercase text-muted-foreground block mb-0.5">
                Executive Summary
              </span>
              <p className="text-xs text-foreground bg-muted/30 p-2 rounded border leading-relaxed">
                {analysis.summary}
              </p>
            </div>

            {/* Identified Objections */}
            {analysis.keyObjections.length > 0 && (
              <div>
                <span className="text-[10px] font-semibold uppercase text-muted-foreground block mb-1">
                  Key Roadblocks & Objections
                </span>
                <ul className="space-y-1">
                  {analysis.keyObjections.map((obj, i) => (
                    <li
                      key={i}
                      className="text-xs text-amber-800 dark:text-amber-300 flex items-start gap-1.5"
                    >
                      <AlertTriangle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
                      <span>{obj}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Suggested Action Items with One-Click Conversion */}
            <div>
              <span className="text-[10px] font-semibold uppercase text-muted-foreground block mb-1">
                Suggested Action Items (Human-in-the-loop)
              </span>
              <div className="space-y-1.5">
                {analysis.actionItems.map((item, i) => {
                  const isAdded = addedTasks.has(i);
                  const isPending = convertingIndex === i;

                  return (
                    <div
                      key={i}
                      className="flex items-center justify-between gap-2 p-2 rounded-md border bg-background text-xs"
                    >
                      <div className="flex items-center gap-2 min-w-0">
                        <Badge
                          variant={item.priority === "high" ? "destructive" : "secondary"}
                          className="text-[9px] px-1 py-0 uppercase shrink-0"
                        >
                          {item.priority}
                        </Badge>
                        <span className="truncate">{item.task}</span>
                        <span className="text-[10px] text-muted-foreground font-mono shrink-0">
                          (Due in {item.dueInDays}d)
                        </span>
                      </div>

                      <Button
                        size="sm"
                        variant={isAdded ? "outline" : "default"}
                        disabled={isAdded || isPending}
                        onClick={() => handleCreateTask(item, i)}
                        className="text-[10px] h-6 px-2 gap-1 shrink-0"
                      >
                        {isAdded ? (
                          <>
                            <CheckCircle className="h-3 w-3 text-emerald-600 dark:text-emerald-400" />
                            Added
                          </>
                        ) : isPending ? (
                          <Loader2 className="h-3 w-3 animate-spin" />
                        ) : (
                          <>
                            <Plus className="h-3 w-3" />
                            Create Task
                          </>
                        )}
                      </Button>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
